### ISSUE TITLE
Provide Plugin in Phonegap Build

### ISSUE THREAD

**Issue by writeosahon** [Telerik-Verified-Plugins/ScreenOrientation#1]
@EddyVerbruggen @rdlauer Hello guys. Please can you provide this updated plugin in the phonegap or cordova plugin registry? I would very much want to use this updated version for my current WP8 app development, and I am building my app in the cloud.

Thanks for your help.
Cheers

**Comment by EddyVerbruggen** [comment]
Hey @writeosahon it seem to be already on the registry, here: http://plugins.cordova.io/#/package/net.yoik.cordova.plugins.screenorientation

If you need any updates to the package on the plugin registry, please open an issue with [the upstream repository](https://github.com/yoik/cordova-yoik-screenorientation), as the author published the plugin himself.

Hth,
Eddy

**Comment by writeosahon** [comment]
Hi @EddyVerbruggen . Thanks for the update

I was hoping you could send a pull/merge request to the original repository, then I would inform the original author to merge and upload to registry.
Please let me know when you've sent the request so I can inform original author.

Thanks so much for all your help

Osahon Okungbowa
Sent from my Windows Phone

-----Original Message-----

**Comment by EddyVerbruggen** [comment]
Here you go!
https://github.com/yoik/cordova-yoik-screenorientation/pull/49

**Comment by writeosahon** [comment]
@EddyVerbruggen Thank you so so much.
I'll keep you posted on this.

Cheers
