### ISSUE TITLE
Getting "Uncaught TypeError: window.screen.lockOrientation is not a function" when implementing lockOrientation

### ISSUE THREAD

**Issue by longpham91** [Telerik-Verified-Plugins/ScreenOrientation#2]
Hi there,

I'm building an app using Telerik AppBuilder w/ Screen Builder support. In order to prevent users from changing the orientation and therefore might mess up the interface, I added ScreenOrientation plugin from Telerik Plugins store and implement it into my app like this:

```
if (window.cordova) {
        // this function is called by Cordova when the application is loaded by the device
        document.addEventListener('deviceready', function() {
            [...]
            window.screen.lockOrientation('portrait');
        }, false);
    }
```

However, I keep getting this error:

```
Uncaught TypeError: window.screen.lockOrientation is not a function
```

I've double-checked that there was no other libraries / plugins missing or conflicting with this. DeviceOrientation plugin is also installed. Looking forward to your reply!

Best regards,

Leo

**Comment by EddyVerbruggen** [comment]
Hi, is there a reason you don't limit your app to portrait by using the orientation settings instead of using this plugin?

And have you really added the plugin (since your usage seems just fine). Or are you running the app inside the companion app perhaps?

**Comment by longpham91** [comment]
Hi @EddyVerbruggen,

Wow that was fast! Anyway, to answer your questions:

1) The design given to me requires that most views are portrait-oriented, but there are 1-2 views that has to be landscape.

2) I've tried adding the plugin using both the AppBuilder CLI and then the AppBuilder IDE. In both cases, the plugin seemed to stick, as proven by the screenshot below (taken from Properties section of the project).

**Comment by longpham91** [comment]
Forgot the screenshot:

<img width="831" alt="2015-09-25_16-42-12" src="https://cloud.githubusercontent.com/assets/2569884/10111851/e548c50e-63a4-11e5-9fac-086e4a017c44.png">

**Comment by EddyVerbruggen** [comment]
Thanks. How do you deploy and run the app? As a standalone ipa/apk on your phone, or differently?

**Comment by longpham91** [comment]
Right now I'm using Telerik Companion App and Safari for debugging.

**Comment by longpham91** [comment]
Sorry. Kept hitting the wrong button...

**Comment by EddyVerbruggen** [comment]
Yeah that what I figured: you can't use (most) third party plugins (including this one) in the companion app (let alone Safari) because it doesn't bundle the plugin. You need to test this as a standalone app on your device.

Hope that helps,
Eddy
