### ISSUE TITLE
Not compiling for iOS on Cordova 4.0.1

### ISSUE THREAD

**Issue by sserdyuk** [Telerik-Verified-Plugins/ScreenOrientation#3]
I am migrating one of the projects to Appbuilder's experimental Cordova set. The plugin fails to build with the message:

> Error: [xcode-build] Compile /Users/builder/.TelerikPluginsCache/net.yoik.cordova.plugins.screenorientation/1.3.3/src/ios/YoikScreenOrientation.m: In file included from /Users/builder/.TelerikPluginsCache/net.yoik.cordova.plugins.screenorientation/1.3.3/src/ios/YoikScreenOrientation.m:24: /Users/builder/.TelerikPluginsCache/net.yoik.cordova.plugins.screenorientation/1.3.3/src/ios/YoikScreenOrientation.h:26:9: fatal error: 'Cordova/CDVShared.h' file not found

**Comment by EddyVerbruggen** [comment]
Reading through the issues of the upstream repo you might want to stick with cordova-ios-3 right now if you need this plugin. Check [this issue](https://github.com/gbenvenuti/cordova-plugin-screen-orientation/issues/84). The build error is fixable but it won't correctly work on iOS9 if I'm reading correctly.

And also note that the Cordova team will attempt to add it as a core plugin soon, [check here](https://issues.apache.org/jira/browse/CB-9528).

**Comment by EddyVerbruggen** [comment]
btw, the compile error is fixed in 1.3.3.1, it's the least I can do, right? :)

**Comment by sserdyuk** [comment]
Thank you for your advise. I will stay away from the experimental version for now.
