### ISSUE TITLE
iOS 9.3.1 breaking changes

### ISSUE THREAD

**Issue by JoeMeeks** [Telerik-Verified-Plugins/ScreenOrientation#4]
This plugin is not working with AppBuilder 2016.2.420.3 and plugin version 1.3.3.1 on iOS 9.3.1 window.screen.lockOrientation('portrait-primary'), window.screen.lockOrientation('landscape'), and window.screen.unlockOrientation() have no effect. The same build running on an Android 5.0.1 device works as expected.

Is this verified plugin so far behind this non-verified version that I should consider switching?

https://github.com/gbenvenuti/cordova-plugin-screen-orientation

![appbuilder-cordova-4 0 0](https://cloud.githubusercontent.com/assets/3031672/14971652/23de261a-1089-11e6-8c5f-8141a4b6293c.png)

**Comment by JoeMeeks** [comment]
After painstakingly upgrading to unofficial plugin version 1.4.1 (screenorientation.js collision with AppBuilder project platform-specific file handling during plugin import of screenorientation.ios.js, screenorientation.android.js,screenorientation.wp8.js  – see http://docs.telerik.com/platform/appbuilder/development-tools/using-the-ides/managing-assets/platform-specific-files/add-platform-specific-file) this still does not work on iOS 9.3.1.

**Comment by EddyVerbruggen** [comment]
Hey Joe, I'm updating this fork today and also add a patch which aims to solve the iOS 9 issue you're seeing.

**Comment by JoeMeeks** [comment]
Wow, thanks for the responsiveness on this issue, Eddy.

I was unable to install the latest version 1.4.1 in the AppBuilder Plugin Marketplace dialog. Upon further inspection of the repo I saw that the plugin.xml had version 1.4.1 so I incremented it and created a PR.

https://github.com/Telerik-Verified-Plugins/ScreenOrientation/pull/5

This issue persists with version 1.4.0 installed from the plugin marketplace.

![appbuilder-plugins-screenorientation](https://cloud.githubusercontent.com/assets/3031672/14992244/01868a8a-111a-11e6-9e4b-ca7c34b21b2a.png)

**Comment by EddyVerbruggen** [comment]
Hey Joe, I wasn't completely done updating the plugin (didn't update the demo app yet so didn't check in an AppBuilder app) but I am a bit surprised 1.4.0/1.4.1 (same code) doesn't fix your problem. It did fix the issue on a local Cordova CLI project.

Let me check the AppBuilder project in a little while and I'll update this issue.

**Comment by EddyVerbruggen** [comment]
Can you try to [clone our demo app](https://github.com/Telerik-Verified-Plugins/ScreenOrientation-DemoApp), build it, and deploy to an iOS 9.3 device? Locking it to landscape and portrait works great (see screenshot below). So I'm starting to think there must be something else causing the trouble you have..

![img_6729](https://cloud.githubusercontent.com/assets/1426370/14993029/333e3150-1169-11e6-93f2-5eb40630e9fa.PNG)

**Comment by JoeMeeks** [comment]
This is working great in the demo app on iOS 9.3. Thanks for the plugin update!
